---
title: "CV"
author: "Rachel Breuer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Personal profile
I’m an enthusiastic and motivated student with interest in biology and medical research. At present, I'm in my third year of studying for a bachelor's degree in Life Science at Hogeschool Utrecht, The Netherlands. I'm specialized in Laboratory animal sciences. I have communication and analytical skills. I'm looking for an intern to utilise my knowledge and experience.

## Education {-}
- Hogeschool Utrecht
- Location: Utrecht, The Netherlands
- Degree: Life Science Bachelor	

## Experience {-}
- Project Genes and Proteins
    - Cell cloning
    - PCR
    - qPCR
    - Cell culture
    - Gel electrophoresis
    - SDS page
    - Fluorescence microscopy

- Haematology
- Tumor cell biology
- Molecular biology
- ELISA
- Western Blot
- Immunology

- Zoological experiments
    - Operation with and without anaesthesia
    - Blood pressure measurement 
    - Langendorff 
    - Muscle nerve preparation in vivo
    - Biliary excretion
    - Blood pressure effect through brain stimulation
	
- Minor Data Science For Biology
    - Next Generation Sequencing
    - Rstudio
    - RNA-sequencing data 
        - Heatmap
        - PCA
        - Volcano plot
        - GO term enrichment analysis 
    - Metagenomics data

## Additional experience {-}
- Ikea - Delft : 2021- Current 
    - Food co-worker 
- McDonald’s - Den Haag : 2019 – 2020
    - Food co-worker


