<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Survival package | Portfolio</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Survival package | Portfolio" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Survival package | Portfolio" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Rachel Breuer" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon32x32.png" type="image/x-icon" />
<link rel="prev" href="personal-profile.html"/>
<link rel="next" href="guerrilla-analytics-principles.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/core-js-2.5.3/shim.min.js"></script>
<script src="libs/react-18.2.0/react.min.js"></script>
<script src="libs/react-18.2.0/react-dom.min.js"></script>
<script src="libs/reactwidget-1.0.0/react-tools.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/reactable-0.4.4/reactable.css" rel="stylesheet" />
<script src="libs/reactable-binding-0.4.4/reactable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Portfolio Rachel Breuer</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introductie</a></li>
<li class="chapter" data-level="1" data-path="personal-profile.html"><a href="personal-profile.html"><i class="fa fa-check"></i><b>1</b> Personal profile</a>
<ul>
<li class="chapter" data-level="" data-path="personal-profile.html"><a href="personal-profile.html#education"><i class="fa fa-check"></i>Education</a></li>
<li class="chapter" data-level="" data-path="personal-profile.html"><a href="personal-profile.html#experience"><i class="fa fa-check"></i>Experience</a></li>
<li class="chapter" data-level="" data-path="personal-profile.html"><a href="personal-profile.html#additional-experience"><i class="fa fa-check"></i>Additional experience</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="survival-package.html"><a href="survival-package.html"><i class="fa fa-check"></i><b>2</b> Survival package</a>
<ul>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#introductie"><i class="fa fa-check"></i>Introductie</a></li>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#dataset"><i class="fa fa-check"></i>Dataset</a>
<ul>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#metadata"><i class="fa fa-check"></i>Metadata</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#kaplan-meier"><i class="fa fa-check"></i>Kaplan-Meier</a>
<ul>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#kaplan-meier-geslacht"><i class="fa fa-check"></i>Kaplan-Meier geslacht</a></li>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#kaplan-meier-leeftijd"><i class="fa fa-check"></i>Kaplan-Meier leeftijd</a></li>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#log-rank-test-op-rokers"><i class="fa fa-check"></i>Log-rank test op rokers</a></li>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#cox-proportional-hazards-model"><i class="fa fa-check"></i>Cox Proportional Hazards Model</a></li>
<li class="chapter" data-level="" data-path="survival-package.html"><a href="survival-package.html#cox-proportional-hazards-model-controle"><i class="fa fa-check"></i>Cox Proportional Hazards Model controle</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="guerrilla-analytics-principles.html"><a href="guerrilla-analytics-principles.html"><i class="fa fa-check"></i><b>3</b> Guerrilla Analytics Principles</a>
<ul>
<li class="chapter" data-level="" data-path="guerrilla-analytics-principles.html"><a href="guerrilla-analytics-principles.html#introductie-1"><i class="fa fa-check"></i>Introductie</a></li>
<li class="chapter" data-level="" data-path="guerrilla-analytics-principles.html"><a href="guerrilla-analytics-principles.html#portfolio-framework"><i class="fa fa-check"></i>Portfolio framework</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="c.-elegans-plate-experiment.html"><a href="c.-elegans-plate-experiment.html"><i class="fa fa-check"></i><b>4</b> C. elegans plate experiment</a>
<ul>
<li class="chapter" data-level="" data-path="c.-elegans-plate-experiment.html"><a href="c.-elegans-plate-experiment.html#stappenplan"><i class="fa fa-check"></i>Stappenplan</a></li>
<li class="chapter" data-level="" data-path="c.-elegans-plate-experiment.html"><a href="c.-elegans-plate-experiment.html#importeren-en-inspecteren"><i class="fa fa-check"></i>Importeren en inspecteren</a></li>
<li class="chapter" data-level="" data-path="c.-elegans-plate-experiment.html"><a href="c.-elegans-plate-experiment.html#scatterplot"><i class="fa fa-check"></i>Scatterplot</a></li>
<li class="chapter" data-level="" data-path="c.-elegans-plate-experiment.html"><a href="c.-elegans-plate-experiment.html#normalized-data"><i class="fa fa-check"></i>Normalized data</a>
<ul>
<li class="chapter" data-level="" data-path="c.-elegans-plate-experiment.html"><a href="c.-elegans-plate-experiment.html#scatterplot-normalized-data"><i class="fa fa-check"></i>Scatterplot normalized data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="open-peer-review.html"><a href="open-peer-review.html"><i class="fa fa-check"></i><b>5</b> Open peer review</a>
<ul>
<li class="chapter" data-level="" data-path="open-peer-review.html"><a href="open-peer-review.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="open-peer-review.html"><a href="open-peer-review.html#repita-criteria"><i class="fa fa-check"></i>‘Repita’-criteria</a></li>
<li class="chapter" data-level="" data-path="open-peer-review.html"><a href="open-peer-review.html#r-code"><i class="fa fa-check"></i>R code</a>
<ul>
<li class="chapter" data-level="" data-path="open-peer-review.html"><a href="open-peer-review.html#review"><i class="fa fa-check"></i>Review</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="r-packages-package.html"><a href="r-packages-package.html"><i class="fa fa-check"></i><b>6</b> R packages (package.rb)</a>
<ul>
<li class="chapter" data-level="" data-path="r-packages-package.html"><a href="r-packages-package.html#installatie"><i class="fa fa-check"></i>Installatie</a></li>
<li class="chapter" data-level="" data-path="r-packages-package.html"><a href="r-packages-package.html#gebruik"><i class="fa fa-check"></i>Gebruik</a></li>
<li class="chapter" data-level="" data-path="r-packages-package.html"><a href="r-packages-package.html#functies"><i class="fa fa-check"></i>Functies</a></li>
<li class="chapter" data-level="" data-path="r-packages-package.html"><a href="r-packages-package.html#voorbeeld"><i class="fa fa-check"></i>Voorbeeld</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="project-antimicrobiële-resistentie.html"><a href="project-antimicrobiële-resistentie.html"><i class="fa fa-check"></i><b>7</b> Project antimicrobiële resistentie</a>
<ul>
<li class="chapter" data-level="" data-path="project-antimicrobiële-resistentie.html"><a href="project-antimicrobiële-resistentie.html#introductie-2"><i class="fa fa-check"></i>Introductie</a></li>
<li class="chapter" data-level="" data-path="project-antimicrobiële-resistentie.html"><a href="project-antimicrobiële-resistentie.html#antimicrobiële-resistentie"><i class="fa fa-check"></i>Antimicrobiële resistentie</a></li>
<li class="chapter" data-level="" data-path="project-antimicrobiële-resistentie.html"><a href="project-antimicrobiële-resistentie.html#r-shiny-app"><i class="fa fa-check"></i>R shiny-app</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="parameterized-report-covid-19.html"><a href="parameterized-report-covid-19.html"><i class="fa fa-check"></i><b>8</b> Parameterized report COVID-19</a>
<ul>
<li class="chapter" data-level="" data-path="parameterized-report-covid-19.html"><a href="parameterized-report-covid-19.html#parametrisatie-lijst"><i class="fa fa-check"></i>Parametrisatie lijst</a></li>
<li class="chapter" data-level="" data-path="parameterized-report-covid-19.html"><a href="parameterized-report-covid-19.html#importeren-en-inspecteren-1"><i class="fa fa-check"></i>Importeren en inspecteren</a></li>
<li class="chapter" data-level="" data-path="parameterized-report-covid-19.html"><a href="parameterized-report-covid-19.html#lijngrafiek-nederland-frankrijk-en-spanje"><i class="fa fa-check"></i>Lijngrafiek Nederland, Frankrijk en Spanje</a></li>
<li class="chapter" data-level="" data-path="parameterized-report-covid-19.html"><a href="parameterized-report-covid-19.html#lijngrafiek-roemenië-noorwegen-en-italië"><i class="fa fa-check"></i>Lijngrafiek Roemenië, Noorwegen en Italië</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="literatuur.html"><a href="literatuur.html"><i class="fa fa-check"></i><b>9</b> Literatuur</a></li>
<li class="divider"></li>
<li><a target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Portfolio</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="survival-package" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Survival package<a href="survival-package.html#survival-package" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introductie" class="section level2 unnumbered hasAnchor">
<h2>Introductie<a href="survival-package.html#introductie" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Over twee jaar wil ik me graag bezighouden met onderzoek over haematologie of oncologie, in combinatie met data science en zoölogie. Bij de minor Data Science leer ik verschillende vaardigheden en technieken, waardoor ik dit kan toepassen in mijn afstudeerstage en later in mijn werk. Ik zou graag willen werken bij een ziekenhuis of universiteit, met name onderzoek over ziektes en medicijnen. Voor mijn afstudeerstage zou ik graag onderzoek willen doen met proefdieren en medicijnen. Met Data Science kunnen we gegevens analyseren en inzichten uit halen, zoals verbeteren van diagnoses en ontdekken van nieuwe manieren om ziektes/ te bestrijden.</p>
<p>Een nieuwe skill die ik graag wil leren is het visualiseren van data. Door nieuwe visualisatietools te ontdekken en toe te passen, zou ik in staat zijn om een nieuw type grafiek te maken en het visualiseren van mijn gegevens te vergemakkelijken. Voor de vrije ruimte ga ik de <code>survival</code> package van R leren. <code>Survival</code> package wordt gebruikt voor het visualiseren van overleveingsanalyses. Met deze package kan je de tijd tot overlijden of optreden van ziektes bestuderen. Dit is handig voor mijn afstudeerstage en op de werkveld. Met behulp van deze skill kan ik met interesse van haematologie/oncologie de verkregen data beter analyseren en gemakkelijker visualiseren.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-1"></span>
<img src="images/survival_curve.png" alt="Kaplan-Meier plot. De Kaplan-Meier plot van de survival package toont aan de cumulatieve overlevingskansen tegenover tijd." width="70%" />
<p class="caption">
Figure 2.1: Kaplan-Meier plot. De Kaplan-Meier plot van de survival package toont aan de cumulatieve overlevingskansen tegenover tijd.
</p>
</div>
<p><br/><br/>
Om de <code>survival</code> package in vier dagen te leren, heb ik de volgende gedaan.Ten eerste heb ik papers en workflows opgezocht over de package, waaronder de website van <span class="citation"><span>“Survminer <span>R</span> Package: <span>Survival</span> <span>Data</span> <span>Analysis</span> and <span>Visualization</span> - <span>Easy</span> <span>Guides</span> - <span>Wiki</span> - <span>STHDA</span>”</span> (<a href="#ref-noauthor_survminer_nodate">n.d.</a>)</span>, waar ik de survival data anylyse heb bestudeerd en visualiseerd. Deze website bood voorbeelden en verschillende functie aan van de package. Daarnaast heb ik een paper van <a href="https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf">Therneau (2024)</a> bestudeerd, genaamd ‘A package for survival analysis in R’. Ik ging op de internet nepdata of bestaande data opzoeken die gerelateerd is op onderzoeken van ziektes met overlevingskans of periode van overlijding. Vervolgens heb ik een paper van <span class="citation">finnstats (<a href="#ref-finnstats_log_2021">2021</a>)</span> gelezen voor uitleg over de log-rank test in R. Met deze functie kan statische testen uitgevoerd worden.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Dag
</th>
<th style="text-align:left;">
Planning
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Dag 1
</td>
<td style="text-align:left;">
Inlezen van meerdere papers en websites met voorbeelden
</td>
</tr>
<tr>
<td style="text-align:left;">
Dag 2
</td>
<td style="text-align:left;">
Bekijken van YouTube video’s en zoeken naar workflows
</td>
</tr>
<tr>
<td style="text-align:left;">
Dag 3
</td>
<td style="text-align:left;">
Zoeken van nepdata en begin maken met een script
</td>
</tr>
<tr>
<td style="text-align:left;">
Dag 4
</td>
<td style="text-align:left;">
Verder aan script werken
</td>
</tr>
</tbody>
</table>
</div>
<div id="dataset" class="section level2 unnumbered hasAnchor">
<h2>Dataset<a href="survival-package.html#dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Hiervoor wordt er gebruik gemaakt van Heart Failure Prediction gegevens van Kaggle website: <a href="https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction">Heart Failure</a>.</p>
<div class="reactable html-widget html-fill-item" id="htmlwidget-19ace1e1efe000622110" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-19ace1e1efe000622110">{"x":{"tag":{"name":"Reactable","attribs":{"data":{"age":[75,55,65,50,65,90,75,60,65,80,75,62,45,50,49,82,87,45,70,48,65,65,68,53,75,80,95,70,58,82,94,85,50,50,65,69,90,82,60,60,70,50,70,72,60,50,51,60,80,57,68,53,60,70,60,95,70,60,49,72,45,50,55,45,45,60,42,72,70,65,41,58,85,65,69,60,70,42,75,55,70,67,60,79,59,51,55,65,44,57,70,60,42,60,58,58,63,70,60,63,65,75,80,42,60,72,55,45,63,45,85,55,50,70,60,58,60,85,65,86,60,66,60,60,60,43,46,58,61,53,53,60,46,63,81,75,65,68,62,50,80,46,50,61,72,50,52,64,75,60,72,62,50,50,65,60,52,50,85,59,66,45,63,50,45,80,53,59,65,70,51,52,70,50,65,60,69,49,63,55,40,59,65,75,58,60.667,50,60,60.667,40,80,64,50,73,45,77,45,65,50,60,63,45,70,60,78,50,40,85,60,49,70,50,78,48,65,73,70,54,68,55,73,65,42,47,58,75,58,55,65,72,60,70,40,53,53,77,75,70,65,55,70,65,40,73,54,61,55,64,40,53,50,55,50,70,53,52,65,58,45,53,55,62,65,68,61,50,55,56,45,40,44,51,67,42,60,45,70,70,50,55,70,70,42,65,50,55,60,45,65,90,45,60,52,63,62,55,45,45,50],"anaemia":[0,0,0,1,1,1,1,1,0,1,1,0,1,1,1,1,1,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,1,1,1,1,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1,0,1,0,0,0,0,0,1,1,1,1,1,1,0,1,1,0,1,0,1,0,1,0,1,1,1,0,0,0,0,1,1,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0,0,1,0,1,1,0,1,0,1,1,0,0,1,0,0,1,1,0,0,1,0,0,1,1,1,0,1,0,0,1,0,1,0,0,0,1,1,1,0,1,0,0,0,0,1,1,0,0,1,1,0,0,0,1,0,0,0,1,1,0,0,0,0,1,1,1,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0],"creatinine_phosphokinase":[582,7861,146,111,160,47,246,315,157,123,81,231,981,168,80,379,149,582,125,582,52,128,220,63,582,148,112,122,60,70,582,23,249,159,94,582,60,855,2656,235,582,124,571,127,588,582,1380,582,553,129,577,91,3964,69,260,371,75,607,789,364,7702,318,109,582,582,68,250,110,161,113,148,582,5882,224,582,47,92,102,203,336,69,582,76,55,280,78,47,68,84,115,66,897,582,154,144,133,514,59,156,61,305,582,898,5209,53,328,748,1876,936,292,129,60,369,143,754,400,96,102,113,582,737,68,96,582,582,358,168,200,248,270,1808,1082,719,193,4540,582,59,646,281,1548,805,291,482,84,943,185,132,1610,582,2261,233,30,115,1846,335,231,58,250,910,129,72,130,582,2334,2442,776,196,66,582,835,582,3966,171,115,198,95,1419,69,122,835,478,176,395,99,145,104,582,1896,151,244,582,62,121,231,582,418,582,167,582,1211,1767,308,97,59,64,167,101,212,2281,972,212,582,224,131,135,582,1202,427,1021,582,582,118,86,582,582,675,57,2794,56,211,166,93,129,707,582,109,119,232,720,180,81,582,90,1185,582,80,2017,143,624,207,2522,572,245,88,446,191,326,132,66,56,66,655,258,157,582,298,1199,135,582,582,582,582,213,64,257,582,618,582,1051,84,2695,582,64,1688,54,170,253,582,892,337,615,320,190,103,61,1820,2060,2413,196],"diabetes":[0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,0,0,0,0,1,1,1,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,1,1,0,0,0,1,0,1,0,0,1,1,0,1,1,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,1,1,0,0,0,1,1,0,1,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,1,1,0,1,1,0,1,0,0,0,1,0,0,0,1,0,1,1,1,0,0,1,0,1,1,0,1,0,1,1,0,0,1,0,1,1,0,1,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,0,0,1,0,1,0,1,0,1,0,1,1,0,0,0,1,1,1,0,0,1,1,1,1,1,0,0,1,0,0,1,1,1,1,0,0,0,0,1,0,1,1,0,1,0,1,1,1,0,1,0,0],"ejection_fraction":[20,38,20,20,20,40,15,60,65,35,38,25,30,38,30,50,38,14,25,55,25,30,35,60,30,38,40,45,38,30,38,45,35,30,50,35,50,50,30,38,20,30,45,50,60,38,25,38,20,30,25,20,62,50,38,30,35,40,20,20,25,40,35,35,80,20,15,25,25,25,40,35,35,50,20,20,60,40,38,45,40,50,25,50,25,50,35,60,40,25,45,45,60,25,38,60,25,60,25,40,25,45,25,30,50,30,45,35,38,35,60,35,25,60,40,40,60,60,60,38,60,38,38,30,40,50,17,60,30,35,60,45,40,60,35,40,60,25,35,30,38,35,30,40,25,30,30,60,30,35,45,60,45,35,35,25,35,25,50,45,40,35,40,35,30,38,60,20,40,35,35,40,60,20,35,60,40,50,60,40,30,25,25,38,25,30,50,25,40,45,35,60,40,30,20,45,38,30,20,35,45,60,60,25,40,45,40,38,40,35,17,62,50,30,35,35,50,70,35,35,20,50,35,25,25,60,25,35,25,25,30,35,35,38,45,50,50,30,40,45,35,30,35,40,38,38,25,25,35,40,30,35,45,35,60,30,38,38,25,50,40,40,25,60,38,35,20,38,38,35,30,40,38,40,30,38,35,38,30,38,40,40,30,38,40,40,35,55,35,38,55,35,38,35,38,38,60,38,45],"high_blood_pressure":[1,0,0,0,0,1,0,0,0,1,1,1,0,1,1,0,0,0,1,0,1,1,1,0,1,0,1,1,0,0,1,0,1,0,1,0,0,1,0,0,1,1,1,1,0,0,1,1,1,0,1,1,0,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,1,1,0,1,1,1,1,0,0,0,0,1,1,1,0,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,0,1,0,1,0,1,0,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,1,1,1,1,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1,1,0,0,0,0,0,1,1,1,0,1,1,1,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],"platelets":[265000,263358.03,162000,210000,327000,204000,127000,454000,263358.03,388000,368000,253000,136000,276000,427000,47000,262000,166000,237000,87000,276000,297000,289000,368000,263358.03,149000,196000,284000,153000,200000,263358.03,360000,319000,302000,188000,228000,226000,321000,305000,329000,263358.03,153000,185000,218000,194000,310000,271000,451000,140000,395000,166000,418000,263358.03,351000,255000,461000,223000,216000,319000,254000,390000,216000,254000,385000,263358.03,119000,213000,274000,244000,497000,374000,122000,243000,149000,266000,204000,317000,237000,283000,324000,293000,263358.03,196000,172000,302000,406000,173000,304000,235000,181000,249000,297000,263358.03,210000,327000,219000,254000,255000,318000,221000,298000,263358.03,149000,226000,286000,621000,263000,226000,304000,850000,306000,228000,252000,351000,328000,164000,271000,507000,203000,263358.03,210000,162000,228000,127000,217000,237000,271000,300000,267000,227000,249000,250000,263358.03,295000,231000,263358.03,172000,305000,221000,211000,263358.03,348000,329000,229000,338000,266000,218000,242000,225000,228000,235000,244000,184000,263358.03,235000,194000,277000,262000,235000,362000,242000,174000,448000,75000,334000,192000,220000,70000,270000,305000,263358.03,325000,176000,189000,281000,337000,105000,132000,267000,279000,303000,221000,265000,224000,219000,389000,153000,365000,201000,275000,350000,309000,260000,160000,126000,223000,263358.03,259000,279000,263358.03,73000,377000,220000,212000,277000,362000,226000,186000,283000,268000,389000,147000,481000,244000,290000,203000,358000,151000,271000,371000,263358.03,194000,365000,130000,504000,265000,189000,141000,237000,274000,62000,185000,255000,330000,305000,406000,248000,173000,257000,263358.03,533000,249000,255000,220000,264000,282000,314000,246000,301000,223000,404000,231000,274000,236000,263358.03,334000,294000,253000,233000,308000,203000,283000,198000,208000,147000,362000,263358.03,133000,302000,222000,263358.03,221000,215000,189000,150000,422000,327000,25100,232000,451000,241000,51000,215000,263358.03,279000,336000,279000,543000,263358.03,390000,222000,133000,382000,179000,155000,270000,742000,140000,395000],"serum_creatinine":[1.9,1.1,1.3,1.9,2.7,2.1,1.2,1.1,1.5,9.4,4,0.9,1.1,1.1,1,1.3,0.9,0.8,1,1.9,1.3,1.6,0.9,0.8,1.83,1.9,1,1.3,5.8,1.2,1.83,3,1,1.2,1,3.5,1,1,2.3,3,1.83,1.2,1.2,1,1.1,1.9,0.9,0.6,4.4,1,1,1.4,6.8,1,2.2,2,2.7,0.6,1.1,1.3,1,2.3,1.1,1,1.18,2.9,1.3,1,1.2,1.83,0.8,0.9,1,1.3,1.2,0.7,0.8,1.2,0.6,0.9,1.7,1.18,2.5,1.8,1,0.7,1.1,0.8,0.7,1.1,0.8,1,1.18,1.7,0.7,1,1.3,1.1,1.2,1.1,1.1,1.18,1.1,1,2.3,1.7,1.3,0.9,1.1,1.3,1.2,1.2,1.6,1.3,1.2,1,0.7,3.2,0.9,1.83,1.5,1,0.75,0.9,3.7,1.3,2.1,0.8,0.7,3.4,0.7,6.1,1.18,1.3,1.18,1.18,0.9,2.1,1,0.8,1.1,0.9,0.9,0.9,1.7,0.7,0.7,1,1.83,0.9,2.5,0.9,0.9,1.18,0.8,1.7,1.4,1,1.3,1.1,1.2,0.8,0.9,0.9,1.1,1.3,0.7,2.4,1,0.8,1.5,0.9,1.1,0.8,0.9,1,1,1,1.2,0.7,0.9,1,1.2,2.5,1.2,1.5,0.6,2.1,1,0.9,2.1,1.5,0.7,1.18,1.6,1.8,1.18,0.8,1,1.8,0.7,1,0.9,3.5,0.7,1,0.8,0.9,1,0.8,1,0.8,1.4,1.6,0.8,1.3,0.9,9,1.1,0.7,1.83,1.1,1.1,0.8,1,1.4,1.3,1,5,1.2,1.7,1.1,0.9,1.4,1.1,1.1,1.1,1.2,1,1.18,1.3,1.3,1.1,0.9,1.8,1.4,1.1,2.4,1,1.2,0.5,0.8,1,1.2,1,1,1.7,1,0.8,0.7,1,0.7,1.4,1,1.2,0.9,1.83,1.7,0.9,1,1.6,0.9,1.2,0.7,1,0.8,1.1,1.1,0.7,1.3,1,2.7,3.8,1.1,0.8,1.2,1.7,1,1.1,0.9,0.8,1.4,1,0.9,1.1,1.2,0.8,1.4,1.6],"serum_sodium":[130,136,129,137,116,132,137,131,138,133,131,140,137,137,138,136,140,127,140,121,137,136,140,135,134,144,138,136,134,132,134,132,128,138,140,134,134,145,137,142,134,136,139,134,142,135,130,138,133,140,138,139,146,134,132,132,138,138,136,136,139,131,139,145,137,127,136,140,142,135,140,139,132,137,134,139,140,140,131,140,136,137,132,133,141,140,137,140,139,144,136,133,137,135,142,141,134,136,137,140,141,137,144,140,143,138,137,138,133,142,132,135,136,137,126,139,136,138,140,134,135,136,140,145,134,135,124,137,136,145,138,131,137,145,137,137,137,130,136,138,134,140,132,141,139,141,136,137,134,136,135,139,134,137,136,140,136,136,134,139,134,139,137,142,139,135,133,134,138,133,136,140,145,139,137,138,135,140,145,140,136,136,136,134,137,136,134,144,136,140,134,135,130,142,135,145,137,138,134,113,137,136,138,136,137,136,141,136,141,130,136,140,138,130,134,134,141,137,134,140,134,145,139,134,138,125,132,140,130,134,127,134,137,137,137,137,148,132,136,137,139,136,136,141,134,137,138,135,142,130,139,143,133,132,139,142,139,139,135,135,138,133,129,140,141,140,134,140,140,132,130,134,133,140,137,137,142,140,136,136,137,136,128,138,141,135,140,132,142,144,141,139,140,136,143,139,138,140,136],"sex":[1,1,1,1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,0,0,0,0,1,1,0,1,0,1,1,1,1,1,0,0,1,1,1,0,1,0,1,0,1,1,0,1,1,1,1,0,1,0,0,0,0,1,1,1,1,1,1,0,1,1,0,1,0,1,0,1,1,1,1,1,1,1,0,1,1,0,0,1,0,1,0,1,1,1,1,1,1,1,0,1,0,1,1,0,0,0,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,1,1,1,0,1,1,1,0,1,0,1,1,0,0,0,1,1,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,1,1,0,1,0,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,0,0,1,0,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,1,0,0,1,1,1,0,1,1,0,0,1,0,1,1,1,1,1,0,1,1,0,0,0,1,1,1,1,1,1,1,0,1,0,1,1,0,1,1,1,1,1,0,0,0,1,0,1,1,0,1,1,1,1,0,1,0,1,1,1,1,0,1,1,0,0,1,1,0,0,1,0,0,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,0,0,1,1],"smoking":[0,0,1,0,0,1,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,0,0,1,0,1,1,1,1,0,0,1,0,0,1,0,1,0,0,1,1,1,1,1,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0,0,1,1,1,0,1,1,1,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,1,0,1,1,0,0,0,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1],"time":[4,6,7,7,8,8,10,10,10,10,10,10,11,11,12,13,14,14,15,15,16,20,20,22,23,23,24,26,26,26,27,28,28,29,29,30,30,30,30,30,31,32,33,33,33,35,38,40,41,42,43,43,43,44,45,50,54,54,55,59,60,60,60,61,63,64,65,65,66,67,68,71,72,72,73,73,74,74,74,74,75,76,77,78,78,79,79,79,79,79,80,80,82,82,83,83,83,85,85,86,87,87,87,87,87,88,88,88,88,88,90,90,90,90,91,91,94,94,94,95,95,95,95,95,96,97,100,104,104,105,106,107,107,107,107,107,107,108,108,108,109,109,109,110,111,112,112,113,113,115,115,117,118,119,120,120,120,120,121,121,121,121,123,126,129,130,134,135,140,145,145,146,146,146,146,146,147,147,147,147,148,150,154,162,170,171,172,172,172,174,174,174,175,180,180,180,185,186,186,186,186,186,186,187,187,187,187,187,187,187,188,192,192,193,194,195,196,196,197,197,198,200,201,201,205,205,205,206,207,207,207,208,209,209,209,209,209,210,210,211,212,212,212,213,213,213,214,214,214,214,214,215,215,215,215,216,220,230,230,231,233,233,235,237,237,240,241,244,244,244,244,244,245,245,245,245,245,246,246,246,247,250,250,250,250,250,250,250,256,256,257,258,258,270,270,271,278,280,285],"DEATH_EVENT":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,0,1,0,1,1,1,1,1,0,0,1,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"columns":[{"id":"age","name":"age","type":"numeric"},{"id":"anaemia","name":"anaemia","type":"numeric"},{"id":"creatinine_phosphokinase","name":"creatinine_phosphokinase","type":"numeric"},{"id":"diabetes","name":"diabetes","type":"numeric"},{"id":"ejection_fraction","name":"ejection_fraction","type":"numeric"},{"id":"high_blood_pressure","name":"high_blood_pressure","type":"numeric"},{"id":"platelets","name":"platelets","type":"numeric"},{"id":"serum_creatinine","name":"serum_creatinine","type":"numeric"},{"id":"serum_sodium","name":"serum_sodium","type":"numeric"},{"id":"sex","name":"sex","type":"numeric"},{"id":"smoking","name":"smoking","type":"numeric"},{"id":"time","name":"time","type":"numeric"},{"id":"DEATH_EVENT","name":"DEATH_EVENT","type":"numeric"}],"defaultPageSize":10,"compact":true,"dataKey":"7b212b87102bcd2440f9c962cc0f169a"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
<div id="metadata" class="section level3 unnumbered hasAnchor">
<h3>Metadata<a href="survival-package.html#metadata" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Leeftijd: leeftijd van de patiënt [jaren]</p></li>
<li><p>Bloedarmoede: afname van rode bloedcellen of hemoglobine [0: False, 1: True]</p></li>
<li><p>Creatinine fosfokinase (CPK): niveau van het CPK-enzym in het bloed [mcg/L]</p></li>
<li><p>Diabetes: of de patiënt diabetes heeft [0: False, 1: True]</p></li>
<li><p>Ejectiefractie: percentage bloed dat bij elke hartslag het hart verlaat [Percentage]</p></li>
<li><p>Hoge bloeddruk: of de patiënt hypertensie heeft [0: False, 1: True]</p></li>
<li><p>Bloedplaatjes: bloedplaatjes in het bloed [kiloplatelets/mL]</p></li>
<li><p>Geslacht: Vrouw of man [0: vrouw, 1: man]</p></li>
<li><p>Serumcreatinine: niveau van serumcreatinine in het bloed [mg/dL]</p></li>
<li><p>Serumnatrium: niveau van serumnatrium in het bloed [mEq/L]</p></li>
<li><p>Roken: of de patiënt rookt of niet [0: False, 1: True]</p></li>
<li><p>Tijd: Follow-up periode [Dagen]</p></li>
<li><p>Overlijdensgebeurtenis: of de patiënt is overleden tijdens de follow-up periode [0: False, 1: True]</p></li>
</ul>
</div>
</div>
<div id="kaplan-meier" class="section level2 unnumbered hasAnchor">
<h2>Kaplan-Meier<a href="survival-package.html#kaplan-meier" class="anchor-section" aria-label="Anchor link to header"></a></h2>
Hieronder is de Kaplan-Meier plot gebaseerd op de data Heart Failure Prediction:
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="_main_files/figure-html/unnamed-chunk-4-1.png" alt="Kaplan-Meier plot van de data Heart Failure Prediction, waarbij de tijd in dagen op de x-as staat, de overlevingskans op de y-as. Verschillende symbolen vertegenwoordigen verschillende experimenttypes." width="672" />
<p class="caption">
Figure 2.2: Kaplan-Meier plot van de data Heart Failure Prediction, waarbij de tijd in dagen op de x-as staat, de overlevingskans op de y-as. Verschillende symbolen vertegenwoordigen verschillende experimenttypes.
</p>
</div>
<p>De resultaat van figuur 2.2 toont de geschatte overlevingskansen van patiënten met hartflaen over tijd. Uit de grafiek blijkt dat de overlevingskans afneemt naarmate de tijd vordert. De curve begint bij een survival waarschijnlijkheid van 1 (of 100%) en daalt geleidelijk naarmate meer sterfgevallen plaatsvinden. Dit leidt op een toenemend aantal sterfgevallen. na circa 200 dagen vlakt de curve af, wat aangeeft ddat de overlevingskansen van de patiënten die deze periode hebben overleefd, stabieler worden. Echter, blijft er nog steeds een risico op overlijden.</p>
<div id="kaplan-meier-geslacht" class="section level3 unnumbered hasAnchor">
<h3>Kaplan-Meier geslacht<a href="survival-package.html#kaplan-meier-geslacht" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-5"></span>
<img src="_main_files/figure-html/unnamed-chunk-5-1.png" alt="Kaplan-Meier plot van de data Heart Failure Prediction gebaseerd op geslacht, waarbij de tijd in dagen op de x-as staat, de overlevingskans op de y-as. Verschillende symbolen vertegenwoordigen verschillende experimenttypes." width="672" />
<p class="caption">
Figure 2.3: Kaplan-Meier plot van de data Heart Failure Prediction gebaseerd op geslacht, waarbij de tijd in dagen op de x-as staat, de overlevingskans op de y-as. Verschillende symbolen vertegenwoordigen verschillende experimenttypes.
</p>
</div>
<p>De resultaat van figuur 2.3 toont de geschatte overlevingskansen van patiënten met hartflaen over tijd bij geslacht. Uit de grafiek blijkt dat bij mannen over het algemeen een iets grotere kans hebben om te overleven dan vrouwen, zowel in de beginperiode als aan het eindeperiode. Echter, bij het bekijken van de risicotabel blijkt dat er relatief meer vrouwen in leven zijn dan mannen naarmate de tijd verstrijkt. Desondanks geeft de grafiek een gemiddeld geschatte grotere overlevingskans voor mannen. als er gekeken wordt naar de risicotabel is er in verhouding meer vrouwen levend dan mannen naarmate tijd, maar dat de grafiek aantoont dat gemiddeld geschat de mannen grotere overlevingskans hebben. De p-waarde van 0.95 duidt op dat er geen significant statistisch verschil is tussen mannen en vrouwen in overlevingskansen bij hartfalen.</p>
</div>
<div id="kaplan-meier-leeftijd" class="section level3 unnumbered hasAnchor">
<h3>Kaplan-Meier leeftijd<a href="survival-package.html#kaplan-meier-leeftijd" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Voor het visualiseren van de plot bij leeftijd wordt eerst gecontroleerd wat de minimale en maximale leeftijd is in de dataset. Dit is nodig voor het categoriseren van leeftijdsgroepen.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="survival-package.html#cb1-1" tabindex="-1"></a><span class="co"># minimaal leeftijd </span></span>
<span id="cb1-2"><a href="survival-package.html#cb1-2" tabindex="-1"></a><span class="fu">min</span>(heart_data<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>## [1] 40</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="survival-package.html#cb3-1" tabindex="-1"></a><span class="co"># maximaal leeftijd</span></span>
<span id="cb3-2"><a href="survival-package.html#cb3-2" tabindex="-1"></a><span class="fu">max</span>(heart_data<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>## [1] 95</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="_main_files/figure-html/unnamed-chunk-7-1.png" alt="Kaplan-Meier plot van de data Heart Failure Prediction gebaseerd op leeftijd, waarbij de tijd in dagen op de x-as staat, de overlevingskans op de y-as. Verschillende symbolen vertegenwoordigen verschillende experimenttypes." width="672" />
<p class="caption">
Figure 2.4: Kaplan-Meier plot van de data Heart Failure Prediction gebaseerd op leeftijd, waarbij de tijd in dagen op de x-as staat, de overlevingskans op de y-as. Verschillende symbolen vertegenwoordigen verschillende experimenttypes.
</p>
</div>
<p>De resultaat van figuur 2.4 toont de geschatte overlevingskansen van patiënten met hartfalen over tijd bij geslacht. Elk lijn vertegenwoordigt een leeftijdsgroep met bijbehorende kleuren voor onderscheiding. Uit de grafiek blijkt dat de overlevingskans van de leeftijdsgroep 40-60 het hoogst is over tijd. Dit wijst erop dat patienten van 40-60 jaar een grotere kans hebben om te overleven. De leeftijdsgroep 60-80 toont een lagere overlevingskansen in dan bij de groep van 40-60, maar heeft een redelijke overlevingkans in circa eerste 150 dagen.
Echter, de leeftijdsgroepen 80-90 jaar en 95+ jaar laten de snelste afname in overleving zien. Vooral de oudste groep van 95 jaar en ouder vertoont een sterke daling, wat resulteert in een hoger risico op overlijden.
Daarnaast is de betrouwbaarheidsinterval van leeftijdsgroep 80-90 het breedst. Dit betekent dat de geschatte overlevingskansen voor deze groep minder nauwkeurig zijn en dat de betrouwbaarheid van de schattingen beperkt kan zijn. De p-waarde &lt; 0.0001 duidt op dat er wel significant statistisch verschil is tussen leeftijdsgroepen in overlevingskansen bij hartfalen.</p>
</div>
<div id="log-rank-test-op-rokers" class="section level3 unnumbered hasAnchor">
<h3>Log-rank test op rokers<a href="survival-package.html#log-rank-test-op-rokers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Met behulp van de log-rank test, kan de significante verschillen in overlevingskansen tussen groepen berekend worden.</p>
<pre><code>## Call:
## survdiff(formula = surv_obj ~ heart_data$smoking)
## 
##                        N Observed Expected (O-E)^2/E (O-E)^2/V
## heart_data$smoking=0 203       66     65.8   0.00064   0.00204
## heart_data$smoking=1  96       30     30.2   0.00139   0.00204
## 
##  Chisq= 0  on 1 degrees of freedom, p= 1</code></pre>
<p>Voor de log-rank test werd de rokers en niet-rokers berekend van significant verschil. De volgende parameters zijn te zien:</p>
<ul>
<li><p>N: Aantal individuen in elke groep</p></li>
<li><p>Observed: Het werkelijke aantal sterfgevallen in elke groep</p></li>
<li><p>Expected: Het verwachte aantal sterfgevallen in elke groep</p></li>
<li><p>(O-E)^2/E: Hoeveelheid voor de afwijking tussen waargenomen en verwachte waarden</p></li>
<li><p>(O-E)^2/V: Een genormaliseerde hoeveelheid voor de afwijking</p></li>
</ul>
<p>De p-waarde is 1, wat aangeeft dat er wel significant statistisch verschil is tussen rokers en niet-rokers in overlevingskansen bij hartfalen.</p>
</div>
<div id="cox-proportional-hazards-model" class="section level3 unnumbered hasAnchor">
<h3>Cox Proportional Hazards Model<a href="survival-package.html#cox-proportional-hazards-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Het Cox Proportional Hazards Model modelleert het effect van verschillende variabelen, zoals leeftijd of roken, op de tijd tot overlijden. Hiermee kunnen we onderzoeken welke variabelen de overlevingskans van patiënten het meest beïnvloeden.</p>
<pre><code>## Call:
## coxph(formula = Surv(time, DEATH_EVENT) ~ age + anaemia + creatinine_phosphokinase + 
##     ejection_fraction + high_blood_pressure + platelets + serum_creatinine + 
##     serum_sodium + sex + smoking, data = heart_data)
## 
##   n= 299, number of events= 96 
## 
##                                coef  exp(coef)   se(coef)      z Pr(&gt;|z|)    
## age                       4.499e-02  1.046e+00  9.007e-03  4.996 5.86e-07 ***
## anaemia                   4.671e-01  1.595e+00  2.171e-01  2.151   0.0314 *  
## creatinine_phosphokinase  2.194e-04  1.000e+00  9.938e-05  2.208   0.0273 *  
## ejection_fraction        -4.884e-02  9.523e-01  1.045e-02 -4.674 2.95e-06 ***
## high_blood_pressure       4.790e-01  1.614e+00  2.162e-01  2.215   0.0267 *  
## platelets                -4.126e-07  1.000e+00  1.125e-06 -0.367   0.7137    
## serum_creatinine          3.118e-01  1.366e+00  6.884e-02  4.529 5.93e-06 ***
## serum_sodium             -4.647e-02  9.546e-01  2.325e-02 -1.998   0.0457 *  
## sex                      -2.447e-01  7.829e-01  2.512e-01 -0.974   0.3300    
## smoking                   1.187e-01  1.126e+00  2.509e-01  0.473   0.6361    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##                          exp(coef) exp(-coef) lower .95 upper .95
## age                         1.0460     0.9560    1.0277    1.0647
## anaemia                     1.5953     0.6268    1.0424    2.4414
## creatinine_phosphokinase    1.0002     0.9998    1.0000    1.0004
## ejection_fraction           0.9523     1.0501    0.9330    0.9720
## high_blood_pressure         1.6144     0.6194    1.0567    2.4664
## platelets                   1.0000     1.0000    1.0000    1.0000
## serum_creatinine            1.3658     0.7322    1.1934    1.5631
## serum_sodium                0.9546     1.0476    0.9121    0.9991
## sex                         0.7829     1.2772    0.4785    1.2811
## smoking                     1.1260     0.8881    0.6886    1.8412
## 
## Concordance= 0.739  (se = 0.027 )
## Likelihood ratio test= 81.56  on 10 df,   p=2e-13
## Wald test            = 87.68  on 10 df,   p=2e-14
## Score (logrank) test = 88.39  on 10 df,   p=1e-14</code></pre>
<p>We onderzoeken de relatie tussen de variabelen (age + anaemia + creatinine_phosphokinase + ejection_fraction + high_blood_pressure +
platelets + serum_creatinine + serum_sodium + sex + smoking) en overlevingstijd (time) tot overlijden (DEATH_EVENT) optreedt. Er zijn 299 patiënten en 96 sterfgevallen.</p>
<p>Hieronder staan enkele belangrijke parameters uit de tabel:</p>
<ul>
<li><p>coef: Geeft aan of een bepaalde variabele het risico op overlijden verhoogt of verlaagt in schatting. Positieve waarden betekenen dat het risico toeneemt naarmate de variabele toeneemt, terwijl negatieve waarden aangeven dat het risico afneemt naarmate de variabele toeneemt.</p></li>
<li><p>exp(coef): Geeft het risico weer in een exponentiële waarde. Een waarde boven 1 betekent een verhoogd risico, en een waarde onder 1 betekent een verlaagd risico.</p></li>
<li><p>Pr(&gt;|z|): Geeft aan of het effect van een variabele statistisch significant is.</p></li>
</ul>
<div id="cox-proportional-hazards-model-resultaten" class="section level4 unnumbered hasAnchor">
<h4>Cox Proportional Hazards Model resultaten<a href="survival-package.html#cox-proportional-hazards-model-resultaten" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p>age: Een verhoging van de leeftijd verhoogt het risico op overlijden met circa 4,6% (exp(coef) = 1.0460). De p-waarde is 5.86e-07, wat duidt op een significant effect. Het 95% betrouwbaarheidsinterval van leeftijd ligt tussen 1.0277 en 1.0647. Aangezien het interval boven de 1 ligt, is het effect van leeftijd positief significant.</p></li>
<li><p>anaemia: Patiënten met bloedarmoede hebben een verhoogd risico op overlijden met circa 59,5% (exp(coef) = 1.5953), met een significante p-waarde van 0.0314. Het 95% betrouwbaarheidsinterval van bloedarmoede ligt tussen 1.0424 en 2.4414. Omdat het interval boven de 1 ligt, is het effect van bloedarmoede positief significant.</p></li>
<li><p>creatinine_phosphokinase: Een verhoging van creatinine fosfokinase geeft een kleine stijging van het risico op overlijden met circa 0,002% (exp(coef) = 1.0002), met een significante p-waarde van 0.0273. Het 95% betrouwbaarheidsinterval van creatinine fosfokinase ligt tussen 1.0000 en 1.0004. Omdat het interval dicht bij de 1 ligt, is het effect van creatinine fosfokinase op het risico op overlijden klein en niet significant.</p></li>
<li><p>ejection_fraction: Een verhoging van de ejectiefractie verlaagt het risico op overlijden met circa 4,8% (exp(coef) = 0.9523). De p-waarde is 2.95e-06, wat duidt op een significant effect. Het 95% betrouwbaarheidsinterval van ejectiefractie ligt tussen 0.9330 en 0.9720. Aangezien het interval onder de 1 ligt, is het effect van een verhoogde ejectiefractie negatief significant.</p></li>
<li><p>high_blood_pressure: Verhoogde bloeddruk leidt tot een verhoogd risico op overlijden met circa 61,4% (exp(coef) = 1.6144). De p-waarde is 0.0267, wat duidt op een significant effect. Het 95% betrouwbaarheidsinterval van bloeddruk ligt tussen 1.0567 en 2.4664. Omdat het interval boven de 1 ligt, is het effect van verhoogde bloeddruk positief significant.</p></li>
<li><p>platelets: Er is geen significant effect op het risico op overlijden. De exp(coef) en p-waarde zijn beide 1. Het 95% betrouwbaarheidsinterval is precies 1, wat betekent dat het effect op het risico op overlijden niet significant is. Bloedplaatjes hebben geen effect op het risico op overlijden.</p></li>
<li><p>serum_creatinine: Een verhoging van serumcreatinineniveau verhoogt het risico op overlijden met circa 36,6% (exp(coef) = 1.3658). De p-waarde is 5.93e-06, wat duidt op een significant effect. Het 95% betrouwbaarheidsinterval van serumcreatinine ligt tussen 1.1934 en 1.5631. Omdat het interval boven de 1 ligt, is het effect van verhoogd serumcreatinineniveau positief significant.</p></li>
<li><p>serum_sodium: Een verhoging van serumnatriumniveau verlaagt het risico op overlijden met circa 4,5% (exp(coef) = 0.9546). De p-waarde is 0.0457, wat duidt op een significant effect. Het 95% betrouwbaarheidsinterval van serumnatrium ligt tussen 0.9121 en 0.9991. Omdat het interval onder de 1 ligt, is het effect van verhoogd serumnatriumniveau negatief significant.</p></li>
<li><p>sex: De p-waarde is 0.3300 &gt; 0.05, waardoor er geen significant effect is op het risico op overlijden. Het 95% betrouwbaarheidsinterval van geslacht ligt tussen 0.4785 en 1.2811. Omdat het interval zowel boven als onder de 1 ligt, is het effect van geslacht niet significant. Geslacht heeft geen effect op het risico op overlijden.</p></li>
<li><p>smoking: De p-waarde is 0.6361 &gt; 0.05, waardoor er geen significant effect is op het risico op overlijden. Het 95% betrouwbaarheidsinterval van roken ligt tussen 0.6886 en 1.8412. Omdat het interval zowel boven als onder de 1 ligt, is het effect van roken niet significant. Roken heeft geen effect op het risico op overlijden.</p></li>
</ul>
<p>De variabelen leeftijd, bloedarmoede, creatinine fosfokinase, ejectiefractie, hoge bloeddruk, serumcreatinine, en serumnatrium tonen aan dat ze significant van invloed zijn op het risico van overlijden bij hartfalenpatiënten. De andere variabelen hebben geen significant effect in dit model. Concordance = 0.739, wat aangeeft hoe betrouwbaar het model voorspelt. 0.739 is dicht bij 1, wat betekent dat het model goed voorspelt.</p>
</div>
</div>
<div id="cox-proportional-hazards-model-controle" class="section level3 unnumbered hasAnchor">
<h3>Cox Proportional Hazards Model controle<a href="survival-package.html#cox-proportional-hazards-model-controle" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Met de <code>coxph</code> functie is het effect van verschillende variabelen op het risico op overlijden geschat. Met de functie <code>cox.zph</code> wordt gecontroleerd of het model correct werkt. De voorwaarde van de <code>coxph</code> functie is dat het effect van de variabelen over tijd gelijk blijft. Als deze voorwaarde niet wordt nageleefd, zouden de resultaten mogelijk niet betrouwbaar zijn. Dit maakt de conclusies betrouwbaarder.</p>
<pre><code>##                             chisq df     p
## age                      9.91e-02  1 0.753
## anaemia                  7.01e-03  1 0.933
## creatinine_phosphokinase 9.85e-01  1 0.321
## ejection_fraction        4.78e+00  1 0.029
## high_blood_pressure      7.74e-03  1 0.930
## platelets                1.95e-05  1 0.996
## serum_creatinine         1.39e+00  1 0.238
## serum_sodium             1.15e-01  1 0.735
## sex                      6.35e-02  1 0.801
## smoking                  4.70e-01  1 0.493
## GLOBAL                   1.16e+01 10 0.316</code></pre>
<p>Van de tabel zijn de volgende onderdelen te zien:</p>
<ul>
<li><p>chisq: Chi-kwadraat-waarde die aangeeft hoeveel afwijking er is van de <code>coxph</code> model</p></li>
<li><p>df: Vrijheidsgraad die op 1 staat. Het geeft aan dat bij elk variabele 1 parameter getest wordt</p></li>
<li><p>p: P-waarde die aangeeft dat de voorwaarde wel of niet geldig is voor die variabele</p></li>
</ul>
<p>Alle variabelen voldoen aan de voorwaarde van het model, behalve “ejection_fraction”. Voor deze variabele is de p-waarde 0.029 &lt; 0.05, wat betekent dat het effect van ejectiefractie niet gelijk is over de tijd op overleving. Ook is de chi-kwadraatwaarde van ejectiefractie hoog, wat kan wijzen op een grote afwijking van de voorwaarde.</p>
<p>Met behulp van de <code>ggcoxzph</code> functie wordt de resultaten van de <code>cox.zph</code> gevisualiseerd.
<img src="_main_files/figure-html/unnamed-chunk-11-1.png" width="1440" />
De horizontale lijn bij de y-as 0 is recht, wat betekent dat er geen significante verandering is in het effect van de variabelen over de tijd. De stippen geven de verschillen weer tussen de voorspelde en werkelijke waarden. De globale Schoenfeld-test p-waarde is 0.3161. Dit geeft aan dat het gehele model goed werkt en dat de voorwaarde van de effecten van de variabelen over de tijd klopt. De meeste stippen blijven dicht bij de horizontale lijn en binnen de gestippelde lijnen (betrouwbaarheidsinterval). Dit betekent dat het effect van deze variabelen over tijd nauwelijks verandert. Enkele grafieken tonen variatie door een aantal stippen die buiten het betrouwbaarheidsinterval liggen, wat mogelijk aangeeft dat het effect van die variabele kan veranderen.</p>

</div>
</div>
</div>
<h3> Literatuur<a href="literatuur.html#literatuur" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-finnstats_log_2021" class="csl-entry">
finnstats. 2021. <span>“Log <span>Rank</span> <span>Test</span> in <span>R</span>-<span>Survival</span> <span>Curve</span> <span>Comparison</span> <span></span> <span>R</span>-Bloggers.”</span> <a href="https://www.r-bloggers.com/2021/08/log-rank-test-in-r-survival-curve-comparison/">https://www.r-bloggers.com/2021/08/log-rank-test-in-r-survival-curve-comparison/</a>.
</div>
<div id="ref-noauthor_survminer_nodate" class="csl-entry">
<span>“Survminer <span>R</span> Package: <span>Survival</span> <span>Data</span> <span>Analysis</span> and <span>Visualization</span> - <span>Easy</span> <span>Guides</span> - <span>Wiki</span> - <span>STHDA</span>.”</span> n.d. Accessed May 26, 2024. <a href="http://www.sthda.com/english/wiki/survminer-r-package-survival-data-analysis-and-visualization">http://www.sthda.com/english/wiki/survminer-r-package-survival-data-analysis-and-visualization</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="personal-profile.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="guerrilla-analytics-principles.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
